apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shopgpt-cloudbuild-service
  namespace: shopgpt
spec:
  template:
    spec:
      serviceAccountName: docker-service-account@shopgpt.iam.gserviceaccount.com
      containers:
      - image: us-west2-docker.pkg.dev/shopgpt/shopgptar/shopgpt-backend

